/** Canonical authenticated app paths (Phase 2 namespace). */
export const appRoutes = {
  dashboard: '/app',
  facilitator: '/app/facilitator',
  sessions: '/app/sessions',
  sessionNew: '/app/sessions/new/setup',
  session: (id: string) => `/app/sessions/${encodeURIComponent(id)}`,
  sessionInvite: (id: string) => `/app/sessions/${encodeURIComponent(id)}/invite`,
  sessionRoom: (id: string) => `/app/sessions/${encodeURIComponent(id)}/control`,
  sessionParticipants: (id: string) => `/app/sessions/${encodeURIComponent(id)}/participants`,
  sessionControl: (id: string) => `/app/sessions/${encodeURIComponent(id)}/control`,
  sessionOutcome: (id: string) => `/app/sessions/${encodeURIComponent(id)}/outcome`,
  sessionRelease: (id: string) => `/app/sessions/${encodeURIComponent(id)}/release`,
  participants: '/app/participants',
  insights: '/app/insights',
  releaseGate: '/app/release-gate',
  appLedger: '/app/ledger',
  executive: '/app/executive',
  ombuds: '/app/ombuds',
  outcomes: '/app/outcomes',
  outcomeNew: '/app/outcomes/new',
  outcome: (id: string) => `/app/outcomes/${encodeURIComponent(id)}`,
  settings: '/app/settings',
} as const;
