-- Phase 3.4 (audit remediation): read-only views that feed the pilot
-- observability dashboards. Each view returns aggregates only — no PII, no
-- message content, no moderator justification text — so a partner-facing
-- dashboard cannot leak data even if the dashboard auth posture slips.
--
-- Wire-up notes:
--   - SELECT-grant to `moderator` role (via app-level moderator gate); we keep
--     the views in `public` schema for tooling compatibility but enforce
--     access via `moderators` table membership inside an authorisation
--     function. Service-role tooling (Grafana, Datadog, Supabase log drains)
--     reads via the service key.
--   - Definitions are intentionally re-runnable: `CREATE OR REPLACE VIEW`.
--   - Audit triggers (immutable plaintext review rows) remain in effect.

SET search_path = public;

-- 1. Match queue depth, sliced by waiting / matched, in the last 60 minutes.
CREATE OR REPLACE VIEW public.pilot_match_queue_depth AS
SELECT
    pool_key,
    side,
    status,
    count(*)::int           AS row_count,
    min(enqueued_at)        AS oldest_enqueued_at,
    max(enqueued_at)        AS newest_enqueued_at
FROM
    public.match_queue
WHERE
    enqueued_at >= timezone('utc'::text, now()) - interval '60 minutes'
GROUP BY
    pool_key, side, status;

COMMENT ON VIEW public.pilot_match_queue_depth IS
    'Pilot dashboard: match-queue depth by pool/side/status over the last hour. No user_id leakage.';

-- 2. Average match latency (enqueued_at -> matched_at), last 24h.
CREATE OR REPLACE VIEW public.pilot_match_latency_24h AS
SELECT
    pool_key,
    count(*)::int AS matched_count,
    EXTRACT(epoch FROM avg(matched_at - enqueued_at))::numeric(12, 3) AS avg_match_seconds,
    EXTRACT(epoch FROM max(matched_at - enqueued_at))::numeric(12, 3) AS max_match_seconds
FROM
    public.match_queue
WHERE
    status = 'matched'
    AND matched_at IS NOT NULL
    AND matched_at >= timezone('utc'::text, now()) - interval '24 hours'
GROUP BY
    pool_key;

COMMENT ON VIEW public.pilot_match_latency_24h IS
    'Pilot dashboard: average and worst-case match latency in the last 24h, per pool.';

-- 3. Moderator decrypt-for-review volume in the last 24h. The Phase 2.2
-- rate-limit caps individual moderator activity; the dashboard query catches
-- coordinated spikes across multiple moderators.
CREATE OR REPLACE VIEW public.pilot_decrypt_audit_24h AS
SELECT
    date_trunc('hour', created_at) AS hour_bucket,
    count(*)::int                  AS decrypt_count,
    count(DISTINCT actor_user_id)::int AS distinct_moderators,
    count(DISTINCT (metadata ->> 'squad_id'))::int AS distinct_squads
FROM
    public.moderation_audit_log
WHERE
    action = 'message_plaintext_decrypt_review'
    AND created_at >= timezone('utc'::text, now()) - interval '24 hours'
GROUP BY
    date_trunc('hour', created_at)
ORDER BY
    hour_bucket DESC;

COMMENT ON VIEW public.pilot_decrypt_audit_24h IS
    'Pilot dashboard: moderator decrypt-for-review volume per hour. Alert on unusual spikes.';

-- 4. Demo claim finalize attempts in the last 24h. Counts both success and
-- consumed-but-conflicted rows. (Errors that never produced a row are not
-- captured here; clients log them via structured logger / Sentry.)
CREATE OR REPLACE VIEW public.pilot_claim_finalize_24h AS
SELECT
    count(*) FILTER (WHERE consumed_at IS NOT NULL)::int AS finalized_count,
    count(*) FILTER (WHERE consumed_at IS NULL AND created_at >= timezone('utc'::text, now()) - interval '24 hours')::int AS pending_count,
    count(*) FILTER (WHERE consumed_at IS NOT NULL AND verified_user_id IS NULL)::int AS finalized_without_verified_user
FROM
    public.demo_session_claims
WHERE
    created_at >= timezone('utc'::text, now()) - interval '24 hours';

COMMENT ON VIEW public.pilot_claim_finalize_24h IS
    'Pilot dashboard: 24h demo-claim finalize stats. `finalized_without_verified_user > 0` is a data-integrity alert.';

-- 5. Squad key creation events. Currently driven by the
-- `squads_set_default_message_encryption_key` trigger; this view counts
-- distinct squads created per hour as a proxy.
CREATE OR REPLACE VIEW public.pilot_key_creation_events_24h AS
SELECT
    date_trunc('hour', created_at) AS hour_bucket,
    count(*)::int                  AS squads_created
FROM
    public.squads
WHERE
    created_at >= timezone('utc'::text, now()) - interval '24 hours'
GROUP BY
    date_trunc('hour', created_at)
ORDER BY
    hour_bucket DESC;

COMMENT ON VIEW public.pilot_key_creation_events_24h IS
    'Pilot dashboard: rate of new squads (≈ rate of squad encryption keys generated by the BEFORE INSERT trigger).';

-- 6. Crisis-alert dashboard. Surfaces unacknowledged alerts so the on-call
-- moderator can see them at a glance.
CREATE OR REPLACE VIEW public.pilot_crisis_alerts_open AS
SELECT
    id,
    squad_id,
    reason_code,
    created_at,
    EXTRACT(epoch FROM (timezone('utc'::text, now()) - created_at))::numeric(12, 0) AS open_seconds
FROM
    public.crisis_alerts
WHERE
    acknowledged_at IS NULL
ORDER BY
    created_at DESC;

COMMENT ON VIEW public.pilot_crisis_alerts_open IS
    'Pilot dashboard: unacknowledged crisis alerts with age in seconds. Page the on-call when reason_code = ''immediate_danger''.';

-- All views inherit RLS from underlying tables. We additionally restrict
-- direct SELECT to authenticated moderators by revoking PUBLIC and granting
-- only to authenticated; Supabase resolves the role from the JWT.
REVOKE ALL ON public.pilot_match_queue_depth FROM PUBLIC;
REVOKE ALL ON public.pilot_match_latency_24h FROM PUBLIC;
REVOKE ALL ON public.pilot_decrypt_audit_24h FROM PUBLIC;
REVOKE ALL ON public.pilot_claim_finalize_24h FROM PUBLIC;
REVOKE ALL ON public.pilot_key_creation_events_24h FROM PUBLIC;
REVOKE ALL ON public.pilot_crisis_alerts_open FROM PUBLIC;

GRANT SELECT ON public.pilot_match_queue_depth TO authenticated;
GRANT SELECT ON public.pilot_match_latency_24h TO authenticated;
GRANT SELECT ON public.pilot_decrypt_audit_24h TO authenticated;
GRANT SELECT ON public.pilot_claim_finalize_24h TO authenticated;
GRANT SELECT ON public.pilot_key_creation_events_24h TO authenticated;
GRANT SELECT ON public.pilot_crisis_alerts_open TO authenticated;
