-- Fix: SECURITY DEFINER on 3 remaining pilot observability views.
--
-- Companion to 20260617000000_fix_security_definer_pilot_views.sql.
-- Same rationale: recreate with security_invoker = true so views execute
-- under the querying user's privileges and respect RLS on underlying tables.
-- No column or query changes from the originals.

-- 1. pilot_claim_finalize_24h (originally: 20260428270000_pilot_observability_views.sql)
CREATE OR REPLACE VIEW public.pilot_claim_finalize_24h
  WITH (security_invoker = true)
AS
SELECT
    count(*) FILTER (WHERE consumed_at IS NOT NULL)::int AS finalized_count,
    count(*) FILTER (WHERE consumed_at IS NULL AND created_at >= timezone('utc'::text, now()) - interval '24 hours')::int AS pending_count,
    count(*) FILTER (WHERE consumed_at IS NOT NULL AND verified_user_id IS NULL)::int AS finalized_without_verified_user
FROM
    public.demo_session_claims
WHERE
    created_at >= timezone('utc'::text, now()) - interval '24 hours';

COMMENT ON VIEW public.pilot_claim_finalize_24h IS
    'Pilot dashboard: 24h demo-claim finalize stats. `finalized_without_verified_user > 0` is a data-integrity alert.';

-- 2. pilot_key_creation_events_24h (originally: 20260428270000_pilot_observability_views.sql)
CREATE OR REPLACE VIEW public.pilot_key_creation_events_24h
  WITH (security_invoker = true)
AS
SELECT
    date_trunc('hour', created_at) AS hour_bucket,
    count(*)::int                  AS squads_created
FROM
    public.squads
WHERE
    created_at >= timezone('utc'::text, now()) - interval '24 hours'
GROUP BY
    date_trunc('hour', created_at)
ORDER BY
    hour_bucket DESC;

COMMENT ON VIEW public.pilot_key_creation_events_24h IS
    'Pilot dashboard: rate of new squads (approx. rate of squad encryption keys generated by the BEFORE INSERT trigger).';

-- 3. pilot_crisis_alerts_open (originally: 20260428270000_pilot_observability_views.sql)
CREATE OR REPLACE VIEW public.pilot_crisis_alerts_open
  WITH (security_invoker = true)
AS
SELECT
    id,
    squad_id,
    reason_code,
    created_at,
    EXTRACT(epoch FROM (timezone('utc'::text, now()) - created_at))::numeric(12, 0) AS open_seconds
FROM
    public.crisis_alerts
WHERE
    acknowledged_at IS NULL
ORDER BY
    created_at DESC;

COMMENT ON VIEW public.pilot_crisis_alerts_open IS
    'Pilot dashboard: unacknowledged crisis alerts with age in seconds. Page the on-call when reason_code = ''immediate_danger''.';

-- Re-apply grants (unchanged from original migrations)
REVOKE ALL ON public.pilot_claim_finalize_24h FROM PUBLIC;
REVOKE ALL ON public.pilot_key_creation_events_24h FROM PUBLIC;
REVOKE ALL ON public.pilot_crisis_alerts_open FROM PUBLIC;

GRANT SELECT ON public.pilot_claim_finalize_24h TO authenticated;
GRANT SELECT ON public.pilot_key_creation_events_24h TO authenticated;
GRANT SELECT ON public.pilot_crisis_alerts_open TO authenticated;
